import Playground from "@/components/Playground";
import Head from "next/head";

const PlaygroundPage: React.FC = () => {
  return (
    <>
      <Head>
        <title>Typing Fight - Playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Playground />
    </>
  );
};

export default PlaygroundPage;
