import Home from "@/components/Home";
import Head from "next/head";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Typing Fight</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Home />
    </>
  );
}
